# cp mongo.repo /etc/yum.repos.d/mongo.repo
# dnf install mongodb-org -y
# sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
# systemctl enable mongod
# systemctl start mongod


- name: Coping repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest

- name: Update mongodb listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes
