# dnf install mysql-server -y
# systemctl enable mysqld
# systemctl start mysqld
# mysql_secure_installation --set-root-pass RoboShop@1


- name: Install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start & enable service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setup Mysql root passwd
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1