# app_pre-req() {
#     useradd roboshop
#     mkdir /app
#     curl -L -o /tmp/${component_name}.zip https://roboshop-artifacts.s3.amazonaws.com/${component_name}-v3.zip
#    cd /app
#    rm -rf /app/*
#    unzip /tmp/${component_name}.zip
#     cd /app
# }



- name: Add Application user
  ansible.builtin.user:
    name: roboshop

- name: Delete old directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract the file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes