#  python() {
#    dnf install python3 gcc python3-devel -y
#    app_pre-req
#    pip3 install -r requirements.txt
#  }

- name: Install python
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: present

- name: Add App pre-requisites
  ansible.builtin.include_tasks:
    file: app_pre-req.yml

- name: Add application dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app