#  systemd_setup() {
#    cp ${pwd}/${component_name}.service /etc/systemd/system/${component_name}.service
#    systemctl daemon-reload
#    systemctl enable ${component_name}
#    systemctl start ${component_name}
#  }


- name: Copy service file
  ansible.builtin.template:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ app_name }}.service


- name: service start
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
    daemon_reload: true
    enabled: yes
