#  java() {
#    dnf install maven -y
#    cp ${pwd}/${component_name}.service /etc/systemd/system/${component_name}.service
#    app_pre-req
#    mvn clean package
#    mv target/shipping-1.0.jar shipping.jar
#  }

- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: Copy service file
  ansible.builtin.copy:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Load App pre-requisites
  ansible.builtin.include_tasks:
    file: app_pre-req.yml

- name: maven packageing
  ansible.builtin.shell: mvn clean package ; mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app