- name: retrieve vault keys
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: get secret kv
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=Demo/data/ssh:username token={{ token }} url=http://vault.prasaddevops.shop:8200') }}"

    - name: get secret kv
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=Demo/data/ssh:passwd token={{ token }} url=http://vault.prasaddevops.shop:8200') }}"