- name: retrieve vault keys
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: get secret kv
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/demo/ssh:username token=${token} url=http://vault.prasaddevops.shop:8200') }}"

#  "{{ lookup('community.hashi_vault.vault_kv2_get', 'demo/ssh', url='http://vault.prasaddevops.shop:8200') }}"